WINES = [
    {
        "name": "Ercole Barbera del Monferrato",
        "vintage": "2024",
        "type": "red",
        "grape": "100% Barbera",
        "grapeDetail": "Barbera is Piedmont's workhorse grape - high acidity, low tannins, makes it incredibly food-friendly",
        "region": "Monferrato, Piedmont",
        "appellation": "Barbera del Monferrato DOC",
        "country": "Italy",
        "winemaker": "Ercole Wines - Named after Ercole (Hercules), referencing the strength and character of Piedmontese wines. This project focuses on bringing authentic Piedmontese varieties to a wider audience, working with local growers who practice sustainable viticulture in the rolling hills of Monferrato. The winery emphasizes minimal intervention and respecting traditional winemaking methods passed down through generations.",
        "tasting": "Bright cherry (morello), raspberry, dried herbs, hints of almond and black pepper. Medium body with high acidity, low tannins, and a refreshing, tangy finish.",
        "food": "Prosciutto di Parma, Felino Salami, Gruyere, Black Truffle Salami, The Basque flatbread",
        "foodPairings": [
            { "item": "Prosciutto di Parma", "why": "Italian wine with Italian ham - high acidity cuts through the fat perfectly" },
            { "item": "Felino Salami", "why": "Both from Northern Italy; the wine's bright acidity balances the salami's richness" },
            { "item": "Gruyere", "why": "Nutty cheese complements the wine's almond hints and herbal notes" },
            { "item": "Black Truffle Salami", "why": "Earthy truffle pairs with the wine's dried herb character" },
            { "item": "The Basque flatbread", "why": "The wine's acidity cuts through rich cheese and prosciutto toppings" }
        ],
        "alcohol": "13%",
        "serving": "Slightly chilled (55-60°F / 13-15°C)",
        "notes": "Barbera is Piedmont's most-planted grape (ahead of Nebbiolo), covering over 50% of the region's vineyards. Its naturally high acidity and low tannins make it incredibly food-friendly and perfect for rich, fatty Italian cuisine. Fun fact: Barbera was once considered a 'peasant grape' but has risen to prominence thanks to modern winemaking. The Monferrato DOC was established in 1994 and sits between the famous Langhe and Asti zones.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Gorghi Tondi Dume",
        "vintage": "2023",
        "type": "red",
        "grape": "100% Frappato",
        "grapeDetail": "Frappato is a light, aromatic Sicilian grape - often blended in Cerasuolo di Vittoria but delicious on its own.",
        "region": "Sicily",
        "appellation": "Sicilia DOC",
        "country": "Italy",
        "winemaker": "Gorghi Tondi - An organic estate in western Sicily. 'Dume' means 'two' in Sicilian dialect, honoring the two founding families who established the estate. Located near the ancient town of Marsala, the vineyards benefit from constant sea breezes that keep vines healthy without chemicals. Gorghi Tondi is passionate about reviving Sicily's indigenous grape varieties, believing they best express the island's sun-drenched Mediterranean character. All wines are certified organic.",
        "tasting": "Fresh red cherry, wild strawberry, rose petals, hints of herbs and Mediterranean scrub. Light body with bright acidity and silky texture.",
        "food": "Prosciutto di Parma, Felino Salami, Saint Angel, Petit Basque, Antipasto Vegetable Blend",
        "foodPairings": [
            { "item": "Prosciutto di Parma", "why": "Light, fruity wine complements delicate ham without overpowering" },
            { "item": "Felino Salami", "why": "Italian salami with Italian wine - bright acidity cuts through the fat" },
            { "item": "Saint Angel", "why": "Rich triple-crème balanced by the wine's fresh acidity and cherry notes" },
            { "item": "Petit Basque", "why": "Mild sheep cheese pairs beautifully with the wine's floral, berry character" },
            { "item": "Antipasto Vegetable Blend", "why": "Italian pickled vegetables with Italian wine - natural aperitivo pairing" }
        ],
        "alcohol": "12.5%",
        "serving": "Slightly chilled (55-60°F / 13-15°C)",
        "notes": "Frappato (frah-PAH-toh) is one of Sicily's indigenous treasures—light-bodied, aromatic, and refreshing, often compared to Beaujolais or Loire reds. It's half of the blend in DOCG Cerasuolo di Vittoria (with Nero d'Avola), but shines solo as a chillable red. The name may come from the Sicilian word for 'to beat or shake'—referring to how the grapes were traditionally harvested. Sicily has more indigenous grape varieties than any other Italian region!",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Heretat Mont-Rubí",
        "vintage": "2022",
        "type": "red",
        "grape": "100% Garnacha (Grenache)",
        "grapeDetail": "Garnatxa is the Catalan name for Grenache/Garnacha - Spain's most planted red grape, known for red fruit and spice.",
        "region": "Penedès (Font-Rubí)",
        "appellation": "Penedès DO",
        "country": "Spain",
        "winemaker": "Heretat Mont-Rubí - A family estate in Font-Rubí, in the heart of Catalonia's Penedès region. 'Heretat' is the Catalan word for estate. The winery has been certified organic since 2002, working with old Garnacha vines that produce small, concentrated berries. The high-altitude vineyards (400-600m) experience dramatic day-night temperature swings that preserve acidity while building ripe fruit character. Heretat Mont-Rubí is part of the new wave of quality-focused Catalan producers.",
        "tasting": "Ripe red berries (raspberry, strawberry), Mediterranean herbs, hints of white pepper and garrigue. Medium body with soft tannins and a warm finish.",
        "food": "Chorizo, Salchichon De Bellota, Ewephoria, Tapenade, Manchego",
        "foodPairings": [
            { "item": "Chorizo", "why": "Spanish wine with Spanish meat - paprika spice complements the wine's peppery notes" },
            { "item": "Salchichon De Bellota", "why": "Rich Ibérico pork matches the wine's fruit and Mediterranean character" },
            { "item": "Ewephoria", "why": "Caramelized cheese notes complement the wine's ripe fruit and soft tannins" },
            { "item": "Tapenade", "why": "Mediterranean flavors unite - olives and herbs echo the wine's garrigue notes" },
            { "item": "Manchego", "why": "Classic Spanish sheep cheese with Spanish Garnacha - regional harmony" }
        ],
        "alcohol": "14%",
        "serving": "Room temperature (60-65°F / 16-18°C)",
        "notes": "Garnacha (Grenache in France, Cannonau in Sardinia) is Spain's most planted red grape—it originated in Aragón and spread across the Mediterranean. Penedès is famous for Cava (sparkling wine), but the high-altitude zones like Font-Rubí are proving excellent for still wines. 'Garnatxa' is the Catalan spelling. The grape produces wines with red fruit, white pepper, and herbal garrigue notes. Old vines (viñas viejas) produce smaller yields but more concentrated, complex wines.",
        "pronunciation": "Heretat: eh-reh-TAHT · Mont-Rubí: mon-roo-BEE · Penedès: peh-neh-DES · Font-Rubí: fon-roo-BEE",
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Red Tail Ridge RTR Estate Vineyard",
        "vintage": "2019",
        "type": "red",
        "grape": "100% Pinot Noir",
        "grapeDetail": "Cool-climate Pinot Noir from the Finger Lakes—elegant, Burgundian in style, from a LEED Gold-certified estate run by a UC Davis grape geneticist.",
        "region": "Finger Lakes",
        "appellation": "Seneca Lake AVA",
        "country": "USA",
        "winemaker": "Nancy Irelan & Mike Schnelle — Nancy holds a PhD in grape genetics from UC Davis (studied under Dr. Carole Meredith, who discovered Cabernet Sauvignon's parentage). She spent 12 years at E&J Gallo rising to VP of Viticulture & Enology R&D before leaving to start Red Tail Ridge on Seneca Lake's western shore. James Beard Award semifinalist. Mike manages the 35-acre estate vineyard with sustainable practices. Their winery was the first LEED Gold-certified in New York State, powered by geothermal energy.",
        "tasting": "Red cherry, raspberry, and rhubarb on the nose. Deep plum and cassis framed by rose petal and spice on the palate. Violet and anise mid-palate with vanilla and smoke on the finish. Light to medium body, silky tannins, bright Finger Lakes acidity. Burgundian elegance.",
        "food": "Prosciutto di Parma, Pâté de Campagne, Petit Basque, Black Truffle Goat, The Basque flatbread",
        "foodPairings": [
            { "item": "Prosciutto di Parma", "why": "Delicate cherry and raspberry fruit mirrors the ham's sweetness; silky tannins complement its buttery fat" },
            { "item": "Pâté de Campagne", "why": "Earthy rustic pâté echoes the wine's violet and smoke notes; bright acidity cuts through the richness" },
            { "item": "Petit Basque", "why": "Mild sheep's milk cheese won't overpower this elegant Pinot; nutty flavors complement the wine's spice" },
            { "item": "Black Truffle Goat", "why": "Truffle's earthy umami pairs beautifully with the wine's plum and anise complexity" },
            { "item": "The Basque flatbread", "why": "Prosciutto and fig jam on the flatbread echo the wine's fruit-forward, savory character" }
        ],
        "alcohol": "13%",
        "serving": "Slightly chilled (55-60°F / 13-16°C)",
        "notes": "Pinot Noir is called the 'Heartbreak Grape' because it's notoriously difficult to grow—thin-skinned, susceptible to disease, and demanding of specific climate conditions. The Finger Lakes succeeds because Seneca Lake (the deepest of the eleven Finger Lakes at 618 feet) acts as a thermal regulator: its massive water volume absorbs summer heat and releases it in autumn, extending the growing season and protecting vines from early frost. Nancy Irelan's mentor Dr. Carole Meredith made history by using DNA profiling to discover that Cabernet Sauvignon is a cross of Cabernet Franc and Sauvignon Blanc. The 2019 vintage was rated 92 points by Wine Enthusiast.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Massimo Ribeira Sacra",
        "vintage": "2023",
        "type": "red",
        "grape": "100% Mencía",
        "grapeDetail": "Mencía is Spain's answer to Pinot Noir - elegant, aromatic, with bright acidity. Native to Galicia and Bierzo.",
        "region": "Ribeira Sacra",
        "appellation": "Ribeira Sacra DO",
        "country": "Spain",
        "winemaker": "Bodegas Massimo - A small, passionate producer farming some of Europe's most dramatic vineyards in Ribeira Sacra. The steep terraced hillsides along the Sil River canyon (slopes up to 60°!) require all work to be done by hand—no tractors can navigate these ancient stone terraces. Many vines are over 80 years old, their roots digging deep into the slate and granite soils. The winery practices sustainable viticulture and focuses exclusively on indigenous Galician varieties.",
        "tasting": "Fresh red berries (raspberry, redcurrant), violets, slate minerality, hints of herbs and wet stone. Medium body with vibrant acidity and fine tannins.",
        "food": "Prosciutto di Parma, Black Pepper Salami, Petit Basque, Duck Rillettes, Saint Angel",
        "foodPairings": [
            { "item": "Prosciutto di Parma", "why": "The wine's bright acidity and red fruit cut through the ham's rich fat" },
            { "item": "Black Pepper Salami", "why": "Pepper spice complements the wine's herbal, mineral notes" },
            { "item": "Petit Basque", "why": "Mild sheep cheese pairs beautifully with the wine's elegant fruit and minerality" },
            { "item": "Duck Rillettes", "why": "Fresh acidity balances the rich duck fat while berry notes complement" },
            { "item": "Saint Angel", "why": "Triple-crème richness is refreshed by the wine's vibrant acidity" }
        ],
        "alcohol": "13%",
        "serving": "Slightly chilled (55-60°F / 13-15°C)",
        "notes": "Ribeira Sacra ('Sacred Riverbank') is named for the many medieval monasteries built along the Sil and Miño river canyons—monks planted these terraced vineyards centuries ago. The region has some of Europe's steepest vineyards, called 'heroic viticulture' because harvesting requires cables and harnesses! Mencía (men-THEE-ah) is often compared to Pinot Noir for its elegance and aromatic complexity. This is one of Spain's most exciting wine regions to watch.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Colle Corviano Montepulciano d'Abruzzo",
        "vintage": "2023",
        "type": "red",
        "grape": "100% Montepulciano",
        "grapeDetail": "NOT to be confused with Vino Nobile di Montepulciano (which uses Sangiovese from Tuscany). This is the Montepulciano GRAPE from Abruzzo.",
        "region": "Abruzzo",
        "appellation": "Montepulciano d'Abruzzo DOC",
        "country": "Italy",
        "winemaker": "Colle Corviano - Part of the Fantini Group (Farnese Vini), one of Abruzzo's most awarded and respected wine producers. Founded in 1994, the Fantini Group has become a benchmark for quality Abruzzo wines, working with over 500 local growers across the region. Their philosophy combines modern winemaking technology with respect for traditional Abruzzese varieties. The vineyards benefit from both Adriatic Sea breezes and the protective Apennine Mountains.",
        "tasting": "Dark cherry, plum, dried herbs (oregano, thyme), earthy notes, hint of black pepper. Medium to full body with moderate tannins and good acidity.",
        "food": "Felino Salami, Prosciutto di Parma, Gruyere, The Basque flatbread, Antipasto Vegetable Blend",
        "foodPairings": [
            { "item": "Felino Salami", "why": "Classic Italian pairing - the wine's herb notes echo traditional salami seasonings" },
            { "item": "Prosciutto di Parma", "why": "Both are Italian classics; the wine's acidity balances the ham's salt and fat" },
            { "item": "Gruyere", "why": "Nutty Swiss cheese complements the wine's earthy, herbal complexity" },
            { "item": "The Basque flatbread", "why": "Prosciutto and fig on the flatbread mirror the wine's fruit and savory balance" },
            { "item": "Antipasto Vegetable Blend", "why": "Italian pickled vegetables match the wine's oregano and thyme herb notes" }
        ],
        "alcohol": "13.5%",
        "serving": "Room temperature (60-65°F / 16-18°C)",
        "notes": "Important distinction: Montepulciano d'Abruzzo is the GRAPE from Abruzzo. Vino Nobile di Montepulciano is a PLACE in Tuscany (using Sangiovese). Don't confuse them! Abruzzo lies on Italy's central Adriatic coast, wild and mountainous. Montepulciano d'Abruzzo is one of Italy's best-value reds—rich, full-flavored wines at friendly prices. The grape produces dark, thick-skinned berries with soft tannins and natural food-friendliness.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Domaine de la Petite Roche Anjou",
        "vintage": "2023",
        "type": "red",
        "grape": "100% Cabernet Franc",
        "grapeDetail": "Anjou (ahn-ZHOO) Cabernet Franc is the Loire's signature red grape—lighter, more aromatic, with red fruit and herbal notes. Called 'Breton' locally.",
        "region": "Anjou, Loire Valley",
        "appellation": "Anjou Rouge AOC",
        "country": "France",
        "winemaker": "Domaine de la Petite Roche - A small family estate in Anjou producing traditional Loire Cabernet Franc with minimal intervention. Sustainable viticulture on schist and sandstone soils, native yeast fermentation, and careful extraction preserve the grape's inherent freshness and aromatic character. Anjou produces a softer, more approachable style of Loire Cabernet Franc—earlier drinking than Bourgueil or Chinon, with more forward fruit and gentle structure.",
        "tasting": "Red currant, fresh raspberry, violet, herbal notes (green leaf, red pepper), and subtle earthy undertones. Medium body with fresh acidity, light tannins, and a vibrant, food-friendly finish.",
        "food": "Duck Rillettes, Pâté de Campagne, Petit Basque, Black Truffle Goat, Prosciutto di Parma",
        "foodPairings": [
            { "item": "Duck Rillettes", "why": "Classic Loire pairing—the wine's acidity cuts through rich duck fat while red fruit complements" },
            { "item": "Pâté de Campagne", "why": "Rustic country pâté matches the wine's earthy, herbal character—traditional French bistro pairing" },
            { "item": "Petit Basque", "why": "Mild sheep cheese won't overpower the wine's delicate raspberry and violet aromatics" },
            { "item": "Black Truffle Goat", "why": "Truffle earthiness harmonizes with the wine's herbal notes and subtle earthy undertones" },
            { "item": "Prosciutto di Parma", "why": "Bright acidity cuts through the ham's salt and fat; red fruit complements the pork's sweetness" }
        ],
        "alcohol": "12.5%",
        "serving": "Slightly chilled (55-60°F / 13-15°C)",
        "notes": "Anjou is the Loire Valley's most diverse wine appellation, producing everything from Muscadet to Chenin Blanc to Cabernet Franc reds. Cabernet Franc is known locally as 'Breton'—legend says Cardinal Richelieu's steward, Father Breton, brought cuttings from Bordeaux in the 17th century. Anjou Rouge tends to be softer and more approachable than Bourgueil or Chinon—lower tannins, brighter fruit, and that quintessential Loire freshness that makes it endlessly food-friendly. Serve slightly chilled for maximum refreshment.",
        "pronunciation": "doh-MEN duh lah puh-TEET ROSH · Anjou: ahn-ZHOO",
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Château Roc Meynard Bordeaux Supérieur",
        "vintage": "2019",
        "type": "red",
        "grape": "70% Merlot, 30% Cabernet Franc",
        "grapeDetail": "Right Bank Bordeaux style with Merlot dominant. Cabernet Franc adds structure and herbal complexity.",
        "region": "Bordeaux Supérieur",
        "appellation": "Bordeaux Supérieur AOC",
        "country": "France",
        "winemaker": "Château Roc Meynard - A historic family estate in the Bordeaux Supérieur appellation, located in the commune of Saint-Seurin-de-Bourg on the Right Bank. The property has been family-owned for five generations, practicing sustainable viticulture on prized clay-limestone soils that provide excellent drainage. The château ages its wines in a combination of French oak barrels and concrete tanks to preserve fruit purity while adding subtle complexity.",
        "tasting": "Red fruits (raspberry, red currant), plum, subtle earthy notes (wet stone), gentle oak, hints of herbs and cedar. Medium body with soft, approachable tannins.",
        "food": "Soppressata Salame w/ Burgundy, Duck Rillettes, Mimolette, Red Wine Cheddar, Ewephoria",
        "foodPairings": [
            { "item": "Soppressata Salame w/ Burgundy", "why": "Wine-infused salami creates harmony with this approachable French red" },
            { "item": "Duck Rillettes", "why": "Soft tannins and fresh acidity balance rich duck fat beautifully" },
            { "item": "Mimolette", "why": "Nutty cheese notes complement the wine's gentle oak and cedar hints" },
            { "item": "Red Wine Cheddar", "why": "Wine-soaked cheese echoes the Bordeaux's red fruit character" },
            { "item": "Ewephoria", "why": "Sweet caramelized notes soften the wine's soft, approachable tannins" }
        ],
        "alcohol": "13.5%",
        "serving": "Room temperature (64°F / 18°C)",
        "notes": "Bordeaux Supérieur has stricter requirements than basic Bordeaux AOC: lower maximum yields (50 vs 55 hl/ha), higher minimum alcohol (10.5% vs 10%), and mandatory aging before release. The 2019 vintage in Bordeaux was exceptional—warm and dry with a long, even growing season, producing wines with ripe tannins and excellent aging potential. Right Bank Bordeaux (like this wine) features Merlot dominance, offering softer, more approachable wines than Left Bank Cabernet blends.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Famiglia Boron",
        "vintage": "2024",
        "type": "white",
        "grape": "100% Pinot Grigio",
        "grapeDetail": "Italian Pinot Grigio is typically fermented in steel for freshness. Same grape as French Pinot Gris but made in a lighter style.",
        "region": "Delle Venezie DOC, Veneto",
        "appellation": "Delle Venezie DOC",
        "country": "Italy",
        "winemaker": "Famiglia Boron - A family-owned winery in northeastern Italy's Veneto region, dedicated to producing authentic, terroir-driven Pinot Grigio. The Boron family has been making wine for generations, combining traditional methods with modern techniques. Their vineyards benefit from the unique microclimate where cool Alpine air meets the Adriatic warmth, creating ideal conditions for crisp, aromatic whites. Stainless steel fermentation preserves the grape's fresh, vibrant character.",
        "tasting": "Crisp green apple, pear, citrus zest, white flowers, and a hint of minerality. Light-bodied with bright acidity and a clean, refreshing finish.",
        "food": "Prosciutto di Parma, Bresaola, Saint Angel, Hummus, Antipasto Vegetable Blend",
        "foodPairings": [
            { "item": "Prosciutto di Parma", "why": "Italian wine with Italian ham - light, crisp wine cuts through salty fat" },
            { "item": "Bresaola", "why": "Delicate lean beef pairs with this neutral, refreshing wine" },
            { "item": "Saint Angel", "why": "Rich cream cheese needs a crisp, clean wine to refresh the palate" },
            { "item": "Hummus", "why": "Neutral wine lets the hummus flavors shine while cleansing the palate" },
            { "item": "Antipasto Vegetable Blend", "why": "Italian pickled veggies with Italian wine - classic aperitivo pairing" }
        ],
        "alcohol": "12%",
        "serving": "Well chilled (45-50°F / 7-10°C)",
        "notes": "Pinot Grigio and Pinot Gris are the same grape—just different styles! Italian Grigio is typically light, crisp, and neutral (stainless steel fermented); Alsatian Gris is richer and more aromatic. Delle Venezie DOC covers Veneto, Friuli, and Trentino—the heart of Italian Pinot Grigio production. Fun fact: Pinot Grigio is a mutation of Pinot Noir; the 'grigio' (gray) refers to the grape's pinkish-gray skin color.",
        "pronunciation": "fah-MEE-lyah boh-ROHN",
        "pronunciationGuideOnly": True,
    },
    {
        "name": "Jean Aubron",
        "vintage": "2023",
        "type": "white",
        "grape": "100% Folle Blanche",
        "grapeDetail": "Folle Blanche is an ancient French grape, once dominant in Cognac before phylloxera. Now thrives in the Loire, producing crisp, high-acid wines.",
        "region": "Loire Valley",
        "appellation": "Gros Plant du Pays Nantais AOP",
        "country": "France",
        "winemaker": "Jean Aubron - A small-production Loire Valley estate dedicated to reviving the Folle Blanche grape. This ancient variety was once France's most planted white grape before phylloxera devastated vineyards in the 1800s. Today it's rare but prized for its bracing acidity and mineral character. The estate practices organic viticulture on chalky clay soils, fermenting in stainless steel to preserve the grape's pure, refreshing character.",
        "tasting": "Crisp green apple, lemon zest, white grapefruit, oyster shell minerality. Light body with electric acidity and a clean, dry finish.",
        "food": "Black Truffle Goat, Hummus, Petit Basque, Maple Bourbon Goat, The Veg flatbread",
        "foodPairings": [
            { "item": "Black Truffle Goat", "why": "High acidity cuts through rich cheese, citrus notes complement earthy truffle" },
            { "item": "Hummus", "why": "Refreshing, crisp wine perfect for casual snacking and dipping" },
            { "item": "Petit Basque", "why": "Mild sheep cheese pairs beautifully with the wine's citrus and mineral notes" },
            { "item": "Maple Bourbon Goat", "why": "The wine's bright acidity balances the cheese's sweet maple notes" },
            { "item": "The Veg flatbread", "why": "Fresh, mineral wine loves vegetable Mediterranean flavors" }
        ],
        "alcohol": "11.5%",
        "serving": "Well chilled (45-50°F / 7-10°C)",
        "notes": "Folle Blanche ('crazy white') got its name because the vines grow vigorously and somewhat wildly. Before phylloxera, it was France's most planted white grape and the primary grape for Cognac. After the devastation, it was largely replaced by Ugni Blanc, which was easier to graft. Today, Folle Blanche survives mainly in Gros Plant du Pays Nantais and a few dedicated producers. Its calling card is razor-sharp acidity—perfect for oysters, seafood, and cutting through rich foods.",
        "pronunciation": "zhahn oh-BROHN fohl BLAHNSH",
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Pouilly-Fumé Dezat",
        "vintage": "2024",
        "type": "white",
        "grape": "100% Sauvignon Blanc",
        "grapeDetail": "Pouilly-Fumé is always 100% Sauvignon Blanc - the 'Fumé' refers to the smoky/flinty character from silex soils, not oak.",
        "region": "Pouilly-Fumé, Loire Valley",
        "appellation": "Pouilly-Fumé AOC",
        "country": "France",
        "winemaker": "Domaine Dezat - A multi-generational family estate in Pouilly-sur-Loire, with roots going back several centuries. The Dezat family owns prime vineyard parcels on the famous silex (flint) soils that give Pouilly-Fumé its distinctive smoky minerality. They practice sustainable viticulture, hand-harvest their grapes, and ferment in temperature-controlled stainless steel to preserve the wine's crystalline purity. The family motto: let the terroir speak through the wine.",
        "tasting": "Citrus (grapefruit, lemon), flint/gunsmoke, white flowers, gooseberry. Bone-dry with razor-sharp acidity, pronounced minerality, and a long, clean finish.",
        "food": "Black Truffle Goat, Petit Basque, Hummus, The Veg flatbread, Bresaola",
        "foodPairings": [
            { "item": "Black Truffle Goat", "why": "THE classic pairing - Loire Sauvignon Blanc and goat cheese are legendary together" },
            { "item": "Petit Basque", "why": "Sheep cheese's mild nuttiness complements the wine's mineral precision" },
            { "item": "Hummus", "why": "Clean, refreshing wine cuts through the tahini richness" },
            { "item": "The Veg flatbread", "why": "Herbal, citrus-driven wine loves fresh vegetable flavors" },
            { "item": "Bresaola", "why": "Lean beef doesn't overpower the wine; acidity brightens the delicate meat" }
        ],
        "alcohol": "13%",
        "serving": "Well chilled (45-50°F / 7-10°C)",
        "notes": "Pouilly-Fumé and Sancerre face each other across the Loire River—both make world-class Sauvignon Blanc but from different soils. The 'fumé' (smoky) name comes from the gunflint character created by silex (flint) soils—strike two pieces together and smell the sulfurous smoke! Loire Sauvignon is bone-dry with laser acidity, unlike sweeter New Zealand styles. Classic pairing secret: Loire Sauvignon + goat cheese (chèvre) is one of wine's most perfect matches.",
        "pronunciation": "poo-YEE foo-MAY deh-ZAH",
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Presqu'ile",
        "vintage": "2023",
        "type": "white",
        "grape": "100% Chardonnay",
        "grapeDetail": "Santa Barbara County Chardonnay benefits from cool Pacific fog, creating a balanced style between rich Napa and lean Burgundy.",
        "region": "Santa Barbara County, California",
        "appellation": "Santa Maria Valley AVA",
        "country": "USA",
        "winemaker": "Presqu'ile Winery - An acclaimed estate winery in California's Santa Maria Valley, founded by the Murphy family in 2007. The name is French for 'almost an island' (peninsula), reflecting the family's French heritage. They farm 73 acres of certified sustainable vineyards on a unique east-west running valley that funnels cool Pacific fog directly over the vines. Their focus is Burgundian varieties (Chardonnay, Pinot Noir) made with minimal intervention: native yeast fermentation, whole-cluster pressing, and judicious French oak aging.",
        "tasting": "Green apple, citrus, white peach, subtle oak (vanilla, toast), hints of butter and minerality. Medium body with balanced acidity and a creamy texture.",
        "food": "Saint Angel, Gruyere, Prosciutto di Parma, Honey Bee Gouda, Duck Rillettes",
        "foodPairings": [
            { "item": "Saint Angel", "why": "Creamy wine with creamy cheese - butter meets butter beautifully" },
            { "item": "Gruyere", "why": "Nutty cheese complements the wine's toasted oak and vanilla notes" },
            { "item": "Prosciutto di Parma", "why": "Rich, balanced Chardonnay stands up to the ham's salt and sweetness" },
            { "item": "Honey Bee Gouda", "why": "Honey sweetness echoes the wine's stone fruit and vanilla character" },
            { "item": "Duck Rillettes", "why": "Rich, buttery wine matches luxurious duck fat perfectly" }
        ],
        "alcohol": "13.5%",
        "serving": "Chilled (50-55°F / 10-13°C)",
        "notes": "Santa Maria Valley is uniquely cool for California—the only valley running east-west, it funnels Pacific Ocean fog deep inland. This creates a Burgundy-like climate perfect for Chardonnay and Pinot Noir. California Chardonnay styles range from rich/oaky (Napa) to lean/mineral (Sonoma Coast). Santa Barbara sits in the middle: balanced, with both fruit and freshness. The 'buttery' character in Chardonnay comes from malolactic fermentation, which converts sharp malic acid to creamy lactic acid.",
        "pronunciation": "press-KEEL",
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Marola Rías Baixas",
        "vintage": "2023",
        "type": "white",
        "grape": "100% Albariño",
        "grapeDetail": "Albariño is Spain's premier white grape, from the rainy, green region of Galicia. Known for bright acidity and stone fruit.",
        "region": "Rías Baixas, Galicia",
        "appellation": "Rías Baixas DO / Val do Salnés",
        "country": "Spain",
        "winemaker": "Bodegas Marola - A small, artisan producer in the Val do Salnés subzone of Rías Baixas, considered the birthplace and heartland of Albariño. The winery farms old vines on decomposed granite soils just kilometers from the Atlantic Ocean, where the maritime influence creates morning fog and constant sea breezes. Traditionally, Albariño vines here are trained on pergolas (parrales) to lift grapes above the damp ground and prevent rot. The wines are fermented in stainless steel to preserve their bright, fresh character.",
        "tasting": "White peach, apricot, citrus (lemon, grapefruit), saline minerality. Medium body with vibrant acidity and a refreshing, slightly briny finish.",
        "food": "Hummus, Tapenade, Prosciutto di Parma, Petit Basque, Antipasto Vegetable Blend",
        "foodPairings": [
            { "item": "Hummus", "why": "Crisp, refreshing wine cleanses the palate between creamy bites" },
            { "item": "Tapenade", "why": "Saline wine echoes the briny olives - Mediterranean coastal harmony" },
            { "item": "Prosciutto di Parma", "why": "Bright acidity cuts through the ham's salt and fat" },
            { "item": "Petit Basque", "why": "Mild sheep cheese pairs with the wine's stone fruit and minerality" },
            { "item": "Antipasto Vegetable Blend", "why": "High acidity matches pickled vegetable tang perfectly" }
        ],
        "alcohol": "12.5%",
        "serving": "Well chilled (45-50°F / 7-10°C)",
        "notes": "Rías Baixas (REE-ahs BY-shus) is in Galicia, Spain's green, Celtic northwest corner—it rains more here than anywhere else in Spain! The 'rías' are fjord-like inlets carved by glaciers, and Atlantic breezes give Albariño its signature saline minerality. Galicians say 'Albariño was born to be paired with seafood'—it's the perfect match for oysters, mussels, and pulpo (octopus). The grape has thick skin to resist the damp climate, giving wines aromatic intensity.",
        "pronunciation": "REE-ahs BY-shus",
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Folly by Mascaronne Rosé Côtes de Provence",
        "vintage": "2024",
        "type": "rose",
        "grape": "Grenache 40%, Cinsault 35%, Mourvèdre 15%, Syrah 10%",
        "grapeDetail": "Classic Provence rosé blend of four traditional grape varieties, direct-pressed for the characteristically pale, delicate Provençal style.",
        "region": "Côtes de Provence",
        "appellation": "Côtes de Provence AOC",
        "country": "France",
        "winemaker": "Château La Mascaronne — Owned by Michel Reybier (who also owns Cos d'Estournel, a Second Growth Bordeaux). NBA legend Tony Parker partnered as winemaker-ambassador in 2022 and co-created the Folly cuvée. Technical Director Nathalie Longefay oversees organic viticulture and winemaking. The estate was previously owned by American Tom Bove, who also formerly owned Château Miraval (later sold to Brad Pitt & Angelina Jolie for $60 million). Certified organic since 2016. Grapes hand-harvested at dawn and sorted twice before pressing.",
        "tasting": "Pale pink with silvery highlights. Honeyed nectarine, white flowers, and pear on the nose. Apricot, fresh citrus, and mineral backbone on the palate. Light and refreshing with a clean, lingering finish.",
        "food": "Prosciutto di Parma, Hummus, Petit Basque, Antipasto Vegetable Blend, The Veg flatbread",
        "foodPairings": [
            { "item": "Prosciutto di Parma", "why": "Delicate pink fruit and minerality complement the ham's sweetness; fresh acidity cuts through the salt" },
            { "item": "Hummus", "why": "Light, refreshing Provence rosé is the quintessential Mediterranean aperitif pairing" },
            { "item": "Petit Basque", "why": "Mild sheep's milk cheese pairs naturally with the wine's nectarine and floral notes" },
            { "item": "Antipasto Vegetable Blend", "why": "Mediterranean vegetables echo the wine's Provençal character and fresh acidity" },
            { "item": "The Veg flatbread", "why": "Fresh vegetable flavors complement this light, mineral-driven rosé" }
        ],
        "alcohol": "13%",
        "serving": "Well chilled (46-50°F / 8-10°C)",
        "notes": "Provence is the birthplace of French rosé and the world's most prestigious rosé-producing region. Most Provence rosés are made by 'direct pressing'—whole grapes are gently pressed and the clear juice fermented like a white wine, producing that signature pale color and delicate flavor (unlike maceration rosés, which soak with the skins). Château La Mascaronne sits at 300 meters altitude in a natural amphitheater of terraced vineyards called 'restanques.' The terroir is chalk and clay over fissured limestone—former owner Tom Bove said: 'I bought here for the rock. To make wine on rock you have to do incredible work, but if you do, you get fabulous results.' The name 'Folly' evokes playful spontaneity. Tony Parker (4x NBA champion with the San Antonio Spurs) brought the brand international visibility.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Grape Abduction Company Orange",
        "vintage": "2024",
        "type": "orange",
        "grape": "Pinot Blanc, Pinot Grigio, Riesling",
        "grapeDetail": "Orange wine (also called skin-contact white) is made by leaving white grape skins in contact with the juice during fermentation — exactly how red wine is made. The result is a wine with white grape aromas, red-wine texture and tannins, and a golden-amber hue. This single-vineyard blend is grown in Štajerska (SHTAH-yer-skah), Slovenia's largest wine region, using natural farming with no chemical inputs.",
        "region": "Štajerska, Slovenia",
        "appellation": "Štajerska",
        "country": "Slovenia",
        "winemaker": "Gönc Winery — Made by Peter Gönc, a 4th-generation winemaker based in Ptuj, the oldest city in Slovenia. The family has been making wine since 1936. The Grape Abduction Company is their natural wine label, imported to the US by JP Bourgeois (Asheville, NC). Grapes are naturally farmed on a single hillside vineyard at 300 feet elevation, fermented with native yeasts, and aged 5 months in stainless steel with minimal sulfites.",
        "tasting": "A light amber color with an aromatically rich nose of ripe golden apple, quince, sweet brown spice, and hints of honey. On the palate, the wine is round with flavors from the nose and a good minerality. The finish is smooth and lingering with highlighted notes of sweet brown spices.",
        "food": "Gruyere, Petit Basque, Mimolette, Prosciutto di Parma, Tapenade",
        "foodPairings": [
            { "item": "Gruyere", "why": "Nutty aged Gruyere meets the wine's honey and brown spice notes — a classic pairing with this skin-contact alpine-adjacent wine" },
            { "item": "Petit Basque", "why": "Mild sheep's milk cheese lets the wine's golden apple and quince aromatics shine without competing" },
            { "item": "Mimolette", "why": "Caramelized butterscotch depth of aged Mimolette harmonizes with the wine's warm amber character and lingering spice" },
            { "item": "Prosciutto di Parma", "why": "The wine's textural grip and honey notes cut through the ham's salt and fat beautifully" },
            { "item": "Tapenade", "why": "Mediterranean olive and herb flavors echo the wine's earthy minerality and round, savory palate" }
        ],
        "alcohol": "12%",
        "serving": "Slightly chilled (52–55°F / 11–13°C)",
        "notes": "Orange wine is one of the most exciting categories in natural wine — and this is a perfect entry point. Made by leaving white grape skins in contact with the juice (the same method used for red wine), the result is amber-hued, textural, and layered in a way that no conventional white can match. The Grape Abduction Company is the natural wine project of Gönc Winery, run by 4th-generation winemaker Peter Gönc from Ptuj, Slovenia — the oldest city in the country. Štajerska is Slovenia's largest wine region, prized for cool-climate aromatic whites that handle skin contact beautifully. Single vineyard, naturally farmed at 300 feet elevation, native yeast fermented, 5 months in stainless steel. No fuss, no tricks — pure Slovenian terroir.",
        "pronunciation": "Štajerska: SHTAH-yer-skah",
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Braunewell Unser Täglich",
        "vintage": "2023",
        "type": "white",
        "grape": "100% Scheurebe",
        "grapeDetail": "Scheurebe is a German crossing of Riesling and an unknown grape. Named after its creator Georg Scheu, it's aromatic with exotic fruit character.",
        "region": "Rheinhessen (Selztal)",
        "appellation": "Rheinhessen QbA",
        "country": "Germany",
        "winemaker": "Weingut Braunewell - A family estate in the Selztal (Selz Valley) of Rheinhessen, Germany's largest and sunniest wine region. Run by the Braunewell family for generations, they specialize in aromatic white varieties. 'Unser Täglich' means 'Our Daily'—a philosophy that great wine should be affordable for everyday enjoyment. The vineyards sit on diverse soils including limestone and loess, and the winery practices sustainable viticulture with minimal intervention in the cellar to preserve aromatic freshness.",
        "tasting": "Grapefruit, passionfruit, elderflower, tropical notes, hint of fresh herbs. Medium body with vibrant acidity and an aromatic, refreshing finish.",
        "food": "Pimento Cheese Dip, Hummus, Maple Bourbon Goat, Exotic Bomba, The Mighty Spicy",
        "foodPairings": [
            { "item": "Pimento Cheese Dip", "why": "Aromatic wine with a touch of sweetness cools jalapeño heat beautifully" },
            { "item": "Hummus", "why": "Exotic fruit notes add interest to the creamy chickpea dip" },
            { "item": "Maple Bourbon Goat", "why": "Sweet cheese with aromatic, fruity wine - complementary flavors" },
            { "item": "Exotic Bomba", "why": "Tropical fruit sorbetto loves tropical-fruited Scheurebe" },
            { "item": "The Mighty Spicy", "why": "Aromatic fruit and vibrant acidity tame the heat from spicy cheddar and chorizo" }
        ],
        "alcohol": "11.5%",
        "serving": "Well chilled (45-50°F / 7-10°C)",
        "notes": "Scheurebe (SHOY-reh-beh) was created in 1916 by Georg Scheu, who crossed Riesling with an unknown variety. For decades it was considered 'Riesling's weird cousin,' but it's having a major renaissance! The grape produces intensely aromatic wines with pink grapefruit, passionfruit, and elderflower—more tropical than Riesling. Rheinhessen is Germany's largest wine region, known for gentle rolling hills called 'Rheinhessische Schweiz' (Rheinhessen Switzerland). Lower alcohol and slight sweetness make it perfect with spicy foods.",
        "pronunciation": "BROW-neh-vel OON-zer TAG-lish SHOY-ray-buh",
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Encomienda de Cervera Horten",
        "vintage": "2023",
        "type": "red",
        "grape": "100% Tempranillo",
        "grapeDetail": "Tempranillo is Spain's noble grape - the backbone of Rioja and Ribera del Duero, known for cherry fruit and aging potential.",
        "region": "Castilla-La Mancha",
        "appellation": "Castilla-La Mancha DO",
        "country": "Spain",
        "winemaker": "Encomienda de Cervera - A historic estate in Castilla-La Mancha, taking its name from an ancient 'encomienda' (medieval land grant from the Spanish crown). The estate dates back centuries and now produces modern, accessible wines from Spain's vast central plateau. 'Horten' refers to their prized garden vineyard parcels, where old-vine Tempranillo grows on chalky, limestone-rich soils. The extreme continental climate (scorching summers, cold winters) stresses vines naturally, concentrating flavors without irrigation.",
        "tasting": "Red cherry, plum, leather, hints of vanilla and tobacco. Medium to full body with moderate tannins and a smooth finish.",
        "food": "Chorizo, Manchego, Ewephoria, Red Wine Cheddar, Salchichon De Bellota",
        "foodPairings": [
            { "item": "Chorizo", "why": "Spanish Tempranillo with Spanish chorizo - classic regional pairing" },
            { "item": "Manchego", "why": "Spain's famous sheep cheese with Spain's noble grape - perfect harmony" },
            { "item": "Ewephoria", "why": "Caramelized notes complement the wine's vanilla and soft tannins" },
            { "item": "Red Wine Cheddar", "why": "Wine-infused cheese echoes the Tempranillo's fruit character" },
            { "item": "Salchichon De Bellota", "why": "Premium Ibérico pork matches this food-friendly Spanish red" }
        ],
        "alcohol": "13.5%",
        "serving": "Room temperature (62-65°F / 17-18°C)",
        "notes": "Tempranillo (tem-prah-NEE-yo) is Spain's noble grape—the backbone of Rioja, Ribera del Duero, and many other regions. The name comes from 'temprano' (early) because it ripens earlier than other Spanish varieties. Castilla-La Mancha is the world's largest wine region by vineyard area—a vast plateau south of Madrid that Don Quixote famously tilted at windmills in. The region offers incredible value: quality wine at everyday prices.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Les Cousins L'Inconscient",
        "vintage": "2023",
        "type": "red",
        "grape": "Grenache, Carignan, Cabernet Sauvignon blend",
        "grapeDetail": "A bold Priorat-style blend from the rising Montsant region, combining power with Mediterranean character.",
        "region": "Montsant",
        "appellation": "Montsant DO",
        "country": "Spain",
        "winemaker": "Marc and Adrià Pérez - Two brothers who created Les Cousins as a passion project with their cousin Gerard while working at their family's main estate, Celler Mas Alta. L'Inconscient ('The Unconscious') represents their philosophy: wines made from intuition and heart, not calculation or market trends. They farm old-vine Grenache and Carignan on the steep slate slopes of Montsant, hand-harvesting everything and using traditional cement and clay amphora fermentation. The wines are bold, authentic, and unapologetically powerful.",
        "tasting": "Dark fruits (blackberry, plum), Mediterranean herbs, licorice, mineral notes from slate soils. Full-bodied with firm tannins and a long, spicy finish.",
        "food": "Chorizo, Salchichon De Bellota, Ewephoria, Mimolette, The Mighty Spicy flatbread",
        "foodPairings": [
            { "item": "Chorizo", "why": "Bold Spanish wine with bold Spanish chorizo - smoky paprika meets dark fruit" },
            { "item": "Salchichon De Bellota", "why": "Rich Ibérico pork can stand up to this powerful, full-bodied wine" },
            { "item": "Ewephoria", "why": "Sweet aged cheese softens the wine's firm tannins" },
            { "item": "Mimolette", "why": "Nutty aged cheese complements the wine's mineral and spice complexity" },
            { "item": "The Mighty Spicy flatbread", "why": "Spicy, bold flavors match this powerful wine's intensity" }
        ],
        "alcohol": "14.5%",
        "serving": "Room temperature (64°F / 18°C), decant 30 min",
        "notes": "Montsant (mont-SAHNT, meaning 'holy mountain') is a DO that literally surrounds Priorat like a donut—same slate/llicorella soils, similar old-vine Grenache and Carignan, but at friendlier prices. Often called 'baby Priorat.' The region was only recognized in 2001 but is rapidly gaining acclaim. The wine's name 'L'Inconscient' reflects the natural wine philosophy: trust the grapes, minimal intervention, let terroir speak. Decanting is recommended to let this powerful wine open up.",
        "pronunciation": "lay koo-ZAN laN-kohn-SYAHN",
        "pronunciationGuideOnly": True,
    },
    {
        "name": "L.A. Cetto",
        "vintage": "2022",
        "type": "red",
        "grape": "100% Cabernet Sauvignon",
        "grapeDetail": "Cabernet Sauvignon thrives in Valle de Guadalupe's warm, Mediterranean-like climate. Mexico's premier wine region produces rich, fruit-forward Cabernet with Old World structure.",
        "region": "Valle de Guadalupe, Baja California",
        "appellation": "Valle de Guadalupe DO",
        "country": "Mexico",
        "winemaker": "L.A. Cetto - Mexico's largest and most internationally acclaimed winery, founded in 1928 by Italian immigrant Angelo Cetto in Valle de Guadalupe. Now in its third generation, L.A. Cetto has won hundreds of medals at international competitions and is widely credited with putting Mexican wine on the world map. The family pioneered quality winemaking in Baja California, importing French varietals and European techniques while embracing the unique Valle de Guadalupe terroir—Mediterranean climate, Pacific Ocean breezes, and mineral-rich soils just 70 miles south of San Diego.",
        "tasting": "Dark blackcurrant, ripe plum, cedar, hints of dark chocolate and tobacco. Medium to full body with firm but polished tannins and a long, satisfying finish.",
        "food": "Chorizo, Manchego, Ewephoria, Salchichon De Bellota, The Mighty Spicy flatbread",
        "foodPairings": [
            { "item": "Chorizo", "why": "Smoky paprika spice meets the wine's dark fruit and firm structure—bold on bold" },
            { "item": "Manchego", "why": "Nutty sheep cheese softens the tannins while complementing the wine's dark fruit" },
            { "item": "Ewephoria", "why": "Caramelized butterscotch notes balance the wine's firm structure and warm finish" },
            { "item": "Salchichon De Bellota", "why": "Rich Ibérico pork fat softens tannins; spice echoes the wine's warm finish" },
            { "item": "The Mighty Spicy flatbread", "why": "Bold wine matches bold flavors—the dark fruit tempers the heat from chorizo and spicy cheddar" }
        ],
        "alcohol": "13.5%",
        "serving": "Room temperature (62-65°F / 17-18°C)",
        "notes": "Valle de Guadalupe is Mexico's premier wine region, located in Baja California just 70 miles south of San Diego. With a Mediterranean climate nearly identical to Southern France, it's ideal for Cabernet Sauvignon. L.A. Cetto was founded in 1928—nearly a century of winemaking history—making it one of Mexico's oldest and most storied producers. The winery helped prove that Mexico could produce world-class wines at a time when most dismissed the country as a wine region. Today, Valle de Guadalupe is increasingly recognized internationally for quality wines at excellent value.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Orsa",
        "vintage": "2020",
        "type": "red",
        "grape": "100% Cabernet Sauvignon",
        "grapeDetail": "Cabernet Sauvignon from Mendocino County's warm inland valleys — ripe and structured, with the freshness that California's north coast climate preserves.",
        "region": "Mendocino County, California",
        "appellation": "Mendocino County AVA",
        "country": "USA",
        "winemaker": "Orsa Wines — A Mendocino County producer focused on crafting approachable, terroir-driven Cabernet Sauvignon from California's northernmost premium wine region. Mendocino has more certified organic wine grape acreage than any other California county — the cool Pacific influence from the coast and the region's clean air create ideal conditions for sustainable farming. The warm days and cool nights of Mendocino's inland valleys develop ripe, structured Cabernet while preserving the natural acidity that keeps the wine fresh and food-friendly.",
        "tasting": "Blackcurrant, dark cherry, ripe plum, hints of cedar and bay leaf. Medium to full body with smooth, polished tannins and a clean, satisfying finish.",
        "food": "Chorizo, Ewephoria, Red Wine Cheddar, Mimolette, The Mighty Spicy flatbread",
        "foodPairings": [
            { "item": "Chorizo", "why": "Smoky paprika and dark fruit make a natural pairing; the wine's structure handles the richness" },
            { "item": "Ewephoria", "why": "Caramelized cheese notes soften the tannins and echo the wine's ripe fruit" },
            { "item": "Red Wine Cheddar", "why": "Wine-infused cheese creates harmony with the Cabernet's dark fruit character" },
            { "item": "Mimolette", "why": "Nutty aged cheese pairs well with the wine's cedar and dark fruit complexity" },
            { "item": "The Mighty Spicy flatbread", "why": "Bold flavors stand up to this medium-full bodied wine" }
        ],
        "alcohol": "13.5%",
        "serving": "Room temperature (62-65°F / 17-18°C)",
        "notes": "Mendocino County is California's northernmost premium wine region — a rugged, largely agricultural county about 100 miles north of San Francisco. It has more certified organic wine grape acreage than any other county in California, earning a reputation for clean, sustainable farming. The region's varied topography creates diverse microclimates: cool coastal valleys for Pinot Noir and Chardonnay, warmer inland valleys (Redwood Valley, Ukiah, Hopland) for Cabernet Sauvignon and Zinfandel. Mendocino Cab tends to show more freshness and structure compared to warmer Napa and Sonoma — same California sunshine, with a cooler north coast edge.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Rocca di Castagnoli Chianti Classico",
        "vintage": "2022",
        "type": "red",
        "grape": "95% Sangiovese, 5% Merlot",
        "grapeDetail": "Chianti Classico requires minimum 80% Sangiovese. The Classico zone is the original, historic heart of Chianti.",
        "region": "Chianti Classico, Tuscany",
        "appellation": "Chianti Classico DOCG",
        "country": "Italy",
        "winemaker": "Rocca di Castagnoli - A historic estate in Gaiole in Chianti, one of Chianti Classico's most prestigious sub-zones. The name means 'Fortress of the Chestnut Trees,' referencing the ancient castle and chestnut forests on the property. The estate dates back to the 10th century and spans 180 hectares at high elevation (400-500m), where cool nights preserve acidity and extend the growing season. They practice sustainable viticulture and use traditional large Slavonian oak barrels (botti) for aging, giving wines elegance rather than new-oak heaviness.",
        "tasting": "Red cherry, dried herbs (oregano, thyme), leather, earthy notes with hints of tobacco. Medium body with firm acidity and well-integrated tannins.",
        "food": "Felino Salami, Prosciutto di Parma, Gruyere, Pecorino Toscano, Antipasto Vegetable Blend",
        "foodPairings": [
            { "item": "Felino Salami", "why": "Italian salami with Tuscan wine - the wine's acidity cuts through the salami's fat" },
            { "item": "Prosciutto di Parma", "why": "Classic Italian pairing; the savory wine complements the ham's sweetness" },
            { "item": "Gruyere", "why": "Nutty cheese balances the wine's bright acidity and herbal character" },
            { "item": "Pecorino Toscano", "why": "Tuscan sheep cheese with Tuscan wine - perfect regional match" },
            { "item": "Antipasto Vegetable Blend", "why": "Italian pickled vegetables designed to pair with Italian wines - natural match" }
        ],
        "alcohol": "13.5%",
        "serving": "Slightly cool room temp (60-64°F / 16-18°C)",
        "notes": "Chianti Classico is the historic heart of Chianti, distinguished by the Gallo Nero (Black Rooster) seal—a symbol dating back to a medieval legend about a border dispute with Siena. The Classico zone requires minimum 80% Sangiovese (vs. 70% for regular Chianti) and produces more structured, age-worthy wines. Sangiovese means 'blood of Jove' and is Italy's most planted red grape. The wine's high acidity and savory character make it one of the world's most food-friendly reds.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Palmeri Navalta Farnacha",
        "vintage": "2018",
        "type": "red",
        "grape": "100% Garnacha (Grenache)",
        "grapeDetail": "Old vine Garnacha from high-altitude Spanish vineyards, showing concentration and complexity.",
        "region": "Calatayud",
        "appellation": "Calatayud DO",
        "country": "Spain",
        "winemaker": "Bodegas Palmeri - A small, quality-driven producer in the mountainous Calatayud region of Aragón. They specialize in old-vine Garnacha, many plants over 50 years old, grown at extreme elevations (800-1000m) on slate and limestone soils. 'Navalta' comes from the Aragonese dialect. The harsh continental climate (scorching days, freezing nights) naturally limits yields and concentrates flavors. Despite Calatayud's ancient winemaking history (dating to Roman times), it only became a DO in 1989 and remains relatively undiscovered.",
        "tasting": "Ripe red and dark fruits (cherry, blackberry), spice, dried herbs, mineral notes. Full body with velvety tannins and a long, warm finish.",
        "food": "Chorizo, Salchichon De Bellota, Ewephoria, Mimolette, Blue d'Auvergne",
        "foodPairings": [
            { "item": "Chorizo", "why": "Spanish wine with Spanish meat - spice and fruit in harmony" },
            { "item": "Salchichon De Bellota", "why": "Rich Ibérico pork can handle this full-bodied, concentrated wine" },
            { "item": "Ewephoria", "why": "Sweet, aged cheese softens the wine's velvety tannins" },
            { "item": "Mimolette", "why": "Nutty cheese depth complements the wine's complex fruit and spice" },
            { "item": "Blue d'Auvergne", "why": "Bold blue cheese needs a powerful wine to match its intensity" }
        ],
        "alcohol": "14.5%",
        "serving": "Room temperature (64°F / 18°C)",
        "notes": "Calatayud (cal-ah-tah-YOOD) is one of Spain's highest wine regions, with vineyards up to 1,000 meters elevation in the Sistema Ibérico mountains. The extreme altitude creates huge temperature swings—up to 25°C between day and night—preserving acidity while building concentration. Old-vine Garnacha (viñas viejas) here can be 80+ years old, producing tiny yields of intensely flavored wine. The 2018 vintage was excellent in Aragón, with balanced growing conditions.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Domaine Verquière Plan de Dieu",
        "vintage": "2024",
        "type": "red",
        "grape": "Grenache 70%, Syrah 20%, Mourvèdre 10%",
        "grapeDetail": "Plan de Dieu is a named village within Côtes du Rhône Villages, known for powerful, concentrated wines from the 'Plain of God.'",
        "region": "Côtes du Rhône Villages Plan de Dieu",
        "appellation": "Côtes du Rhône Villages AOC",
        "country": "France",
        "winemaker": "Domaine Verquière - A family estate in the Rhône Valley since 1960, now run by third-generation winemaker Louis Bernard. Located in the village of Sablet, they own prime parcels in the prestigious Plan de Dieu appellation. The estate practices sustainable viticulture on the plateau's famous galets roulés (large round stones) that store heat during the day and radiate it back at night. Fermentation uses traditional cement tanks and large oak foudres, with the goal of expressing pure terroir rather than winemaker intervention.",
        "tasting": "Dark fruits (blackberry, black cherry), garrigue herbs (thyme, rosemary), black pepper, hints of licorice. Full-bodied with ripe tannins and a long, spicy finish.",
        "food": "Chorizo, Salchichon De Bellota, Ewephoria, Mimolette, Tapenade",
        "foodPairings": [
            { "item": "Chorizo", "why": "Smoky paprika spice complements the wine's peppery, herbal character" },
            { "item": "Salchichon De Bellota", "why": "Rich Ibérico pork matches the wine's full body and dark fruit intensity" },
            { "item": "Ewephoria", "why": "Sweet, aged cheese softens the wine's ripe tannins" },
            { "item": "Mimolette", "why": "Nutty, caramel notes echo the wine's warm, lingering finish" },
            { "item": "Tapenade", "why": "Briny olives and capers match the wine's Mediterranean herb profile" }
        ],
        "alcohol": "14.5%",
        "serving": "Room temperature (62-65°F / 17-18°C)",
        "notes": "Plan de Dieu ('Plain of God') is one of the 22 named villages within Côtes du Rhône Villages—a step up from basic Côtes du Rhône. The name dates to medieval times when Knights Templar monks cultivated vines here on their way to the Crusades. The terroir features galets roulés (large river stones) that act like heat batteries, keeping vines warm at night. The classic Southern Rhône GSM blend (Grenache-Syrah-Mourvèdre) creates wines with dark fruit, spice, and characteristic garrigue herbs.",
        "pronunciation": "vair-kee-AIR plahn duh DYUH",
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Cims de Porrera Vi de Vila Priorat",
        "vintage": "2020",
        "type": "red",
        "grape": "Carinyena (Carignan) 60%, Garnatxa Negra (Grenache) 40%",
        "grapeDetail": "Carinyena (kah-rin-YEH-nah) — the Catalan name for Carignan — and Garnatxa Negra (Grenache) are the two native grapes of Priorat, grown on old vines (10-60+ years) across 22 separate vineyard plots in the village of Porrera.",
        "region": "Priorat DOQ",
        "appellation": "DOQ Priorat / Vi de Vila Porrera",
        "country": "Spain",
        "winemaker": "Cims de Porrera — Founded in 1996 by Josep Lluís Pérez (one of Priorat's five original pioneers who revived the region in the 1980s, also of Mas Martinet) and Lluís Llach (legendary Catalan singer-songwriter whose protest song 'L'Estaca' became an anthem of resistance against Franco). Now run by second-generation cousins Adrià and Marc Pérez. The winery partners with 18 cooperative growers to rescue ancient vines on extreme 40-60% gradient slate slopes. Hand-harvest only. Native yeast fermentation.",
        "tasting": "Intense cherry-red color. Ripe red fruits, wild berries, and violets on the nose. Full-bodied with bramble, plum, black pepper, and balsamic nuances. Velvety tannins, fresh acidity, and distinctive llicorella slate minerality. Long, persistent finish.",
        "food": "Chorizo, Salchichón De Bellota, Ewephoria, Soppressata Salame w/ Burgundy, The Mighty Spicy flatbread",
        "foodPairings": [
            { "item": "Chorizo", "why": "Spanish paprika and garlic in chorizo is a natural regional pairing with this bold Priorat" },
            { "item": "Salchichón De Bellota", "why": "Rich Ibérico acorn-fed pork complements the wine's dark fruit depth and peppery spice" },
            { "item": "Ewephoria", "why": "Aged sheep Gouda's butterscotch and caramel notes balance the wine's powerful minerality" },
            { "item": "Soppressata Salame w/ Burgundy", "why": "Wine-infused salami echoes the wine's dark fruit and balsamic complexity" },
            { "item": "The Mighty Spicy flatbread", "why": "Bold spicy flavors stand up to this full-bodied, high-alcohol Priorat" }
        ],
        "alcohol": "15%",
        "serving": "Slightly cool (54-59°F / 12-15°C)",
        "notes": "DOQ Priorat is one of only two Spanish wine regions with the highest DOCa/DOQ classification (alongside Rioja). The region was nearly abandoned until five pioneers—René Barbier, Álvaro Palacios, Josep Lluís Pérez, Daphne Glorian, and Carles Pastrana—arrived in the late 1980s and revived it. The secret is 'llicorella'—a unique soil of broken black slate and quartz that forces vine roots deep for water, producing tiny yields of incredibly concentrated fruit. 'Vi de Vila' means 'Wine of the Village' in Catalan, a classification system inspired by Burgundy that maps wines to specific village terroirs. Porrera is one of Priorat's 12 villages.",
        "pronunciation": "SEEMS deh poh-REH-rah VEE deh VEE-lah pree-oh-RAHT",
        "pronunciationGuideOnly": False,
    },
    {
        "name": "François Montand Blanc de Blancs",
        "vintage": "NV",
        "type": "sparkling",
        "grape": "100% Chardonnay",
        "grapeDetail": "Blanc de Blancs means 'white from whites' - made exclusively from white grapes (Chardonnay)",
        "region": "Jura",
        "appellation": "Crémant du Jura AOC",
        "country": "France",
        "winemaker": "François Montand - A family-owned producer in the Jura region of Eastern France, known for producing high-quality sparkling wines using traditional methods. The Jura sits in the foothills of the Alps, with unique terroir and a winemaking tradition dating back centuries.",
        "tasting": "Crisp green apple, citrus, white flowers, brioche, fine persistent bubbles. Light-bodied, refreshing with bright acidity and a clean mineral finish.",
        "food": "Oysters, Aged Goat Cheese, Prosciutto, Caviar",
        "foodPairings": [
            { "item": "Oysters", "why": "Briny minerality matches the wine's clean, crisp acidity" },
            { "item": "Aged Goat Cheese", "why": "Tangy cheese pairs with the wine's citrus notes and refreshing bubbles" },
            { "item": "Prosciutto", "why": "Delicate bubbles cut through the ham's salt and fat" },
            { "item": "Caviar", "why": "Classic luxury pairing - the wine's minerality complements the sea-brine of caviar" }
        ],
        "alcohol": "12%",
        "serving": "Well chilled (40-45°F / 4-7°C)",
        "notes": "Blanc de Blancs sparkling wines are prized for their elegance and finesse. Made using the traditional method (méthode traditionnelle), the wine undergoes secondary fermentation in bottle, creating fine, persistent bubbles. The Jura region is also famous for its unique Vin Jaune and has a long history of sparkling wine production rivaling Champagne.",
        "pronunciation": "frahn-SWAH mon-TAHN blahn duh BLAHN",
        "pronunciationGuideOnly": False,
    },
    {
        "name": "L.A. Cetto Brut",
        "vintage": "NV",
        "type": "sparkling",
        "grape": "Chenin Blanc, Colombard",
        "grapeDetail": "Mexican sparkling wine blending Chenin Blanc's honeyed notes with Colombard's bright acidity",
        "region": "Valle de Guadalupe, Baja California",
        "appellation": "Valle de Guadalupe DO",
        "country": "Mexico",
        "winemaker": "L.A. Cetto - Mexico's largest and most acclaimed winery, founded in 1928 by Italian immigrant Angelo Cetto in the Valle de Guadalupe. Now run by the third generation, the winery has put Mexican wines on the international map, winning numerous awards for their quality and value.",
        "tasting": "Fresh pear, green apple, tropical hints, citrus zest. Light-bodied with lively bubbles, crisp acidity, and a clean refreshing finish.",
        "food": "Ceviche, Fish Tacos, Manchego, Fresh Fruit",
        "foodPairings": [
            { "item": "Ceviche", "why": "Mexican wine with Mexican cuisine - citrus notes echo the lime-cured fish" },
            { "item": "Fish Tacos", "why": "Light bubbles and bright acidity cut through the richness of fried fish" },
            { "item": "Manchego", "why": "Nutty sheep's milk cheese complements the wine's pear and apple notes" },
            { "item": "Fresh Fruit", "why": "Tropical hints in the wine pair naturally with fresh fruit desserts" }
        ],
        "alcohol": "12%",
        "serving": "Well chilled (40-45°F / 4-7°C)",
        "notes": "Valle de Guadalupe is Mexico's premier wine region, located in Baja California just 70 miles south of San Diego. The region has a Mediterranean climate similar to Southern France, producing world-class wines that have gained international recognition. L.A. Cetto pioneered quality winemaking in Mexico and remains the country's flagship producer.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Tiamo Prosecco Split",
        "vintage": "NV",
        "type": "sparkling",
        "grape": "100% Glera",
        "grapeDetail": "Glera is the grape variety used in Prosecco - light, fruity, and refreshing",
        "region": "Veneto",
        "appellation": "Prosecco DOC",
        "country": "Italy",
        "winemaker": "Tiamo Wines - An organic Italian producer focused on sustainable, environmentally-friendly winemaking. Tiamo means 'I love you' in Italian, reflecting their love for the land and commitment to producing quality wines without harmful chemicals.",
        "tasting": "Fresh green apple, white peach, pear, delicate floral notes. Light-bodied with soft, frothy bubbles and a crisp, dry finish.",
        "food": "Prosciutto, Bruschetta, Light Appetizers, Brunch dishes",
        "foodPairings": [
            { "item": "Prosciutto", "why": "Classic Italian pairing - bubbles and acidity cut through the salty, fatty ham" },
            { "item": "Bruschetta", "why": "Fresh tomatoes and basil complement the wine's fruity, refreshing character" },
            { "item": "Light Appetizers", "why": "Prosecco's versatility makes it perfect for aperitivo-style snacks" },
            { "item": "Brunch dishes", "why": "The perfect brunch sparkler - pairs with everything from eggs to pastries" }
        ],
        "alcohol": "11%",
        "serving": "Well chilled (38-45°F / 3-7°C)",
        "notes": "Prosecco is made using the Charmat method (tank fermentation) rather than traditional bottle fermentation, giving it lighter, frothier bubbles than Champagne. Split bottles (187ml) are perfect single servings. Tiamo's organic certification means no synthetic pesticides or fertilizers are used in the vineyard, resulting in a pure expression of the Glera grape.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
    {
        "name": "Prosecco DOC",
        "vintage": "NV",
        "type": "sparkling",
        "grape": "100% Glera",
        "grapeDetail": "The signature grape of Italy's most popular sparkling wine",
        "region": "Veneto/Friuli Venezia Giulia",
        "appellation": "Prosecco DOC",
        "country": "Italy",
        "winemaker": "Traditional Italian producer from the Prosecco DOC region, which spans the Veneto and Friuli Venezia Giulia regions of northeastern Italy. The DOC designation ensures quality standards and regional authenticity.",
        "tasting": "Crisp green apple, pear, white flowers, citrus, hint of almond. Light and refreshing with fine, persistent bubbles and bright acidity.",
        "food": "Cheese boards, Seafood, Light Pasta, Celebrations",
        "foodPairings": [
            { "item": "Cheese boards", "why": "Versatile bubbles pair with a variety of cheeses from mild to aged" },
            { "item": "Seafood", "why": "Crisp acidity and light body complement shellfish and light fish dishes" },
            { "item": "Light Pasta", "why": "Refreshing palate cleanser between bites of creamy or oily pasta" },
            { "item": "Celebrations", "why": "The quintessential celebration wine - festive, approachable, and crowd-pleasing" }
        ],
        "alcohol": "11%",
        "serving": "Well chilled (38-45°F / 3-7°C)",
        "notes": "Prosecco is Italy's answer to Champagne, though made differently using the Charmat method for tank fermentation. The DOC (Denominazione di Origine Controllata) designation was established in 2009 to protect the Prosecco name and ensure quality standards. Prosecco must contain at least 85% Glera grapes, with the remaining 15% from other approved local varieties.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
    },
]

ARCHIVED_WINES = [
    {
        "name": "Gorghi Tondi Rosa Dei Venti",
        "vintage": "2023",
        "type": "rose",
        "grape": "100% Nerello Mascalese",
        "grapeDetail": "Nerello Mascalese (neh-REL-oh mas-kah-LEH-zeh) is Sicily's most elegant red grape, best known for Etna Rosso. As a rosé, it yields a delicate pale pink wine with floral aromatics and saline minerality.",
        "region": "Sicily",
        "appellation": "Sicilia DOC",
        "country": "Italy",
        "winemaker": "Gorghi Tondi - An organic estate in western Sicily near Marsala. 'Rosa Dei Venti' means 'Rose of the Winds'—a nod to the constant Mediterranean sea breezes that cool the vineyards and keep vines healthy without chemicals. Gorghi Tondi is passionate about reviving Sicily's indigenous grape varieties, believing they best express the island's sun-drenched Mediterranean character. Certified organic, all grapes are hand-harvested and direct-pressed to achieve the delicate pale color and fresh aromatics.",
        "tasting": "Pale coral pink. Wild strawberry, white peach, citrus blossom, and saline sea spray on the nose. Light-bodied with vibrant acidity and a clean, mineral finish.",
        "food": "Prosciutto di Parma, Petit Basque, Hummus, Antipasto Vegetable Blend, The Veg flatbread",
        "foodPairings": [
            { "item": "Prosciutto di Parma", "why": "Delicate pink fruit and saline minerality mirror the ham's sweetness; acidity cuts through salt" },
            { "item": "Petit Basque", "why": "Mild sheep's milk cheese pairs naturally with the wine's floral and citrus notes" },
            { "item": "Hummus", "why": "Light, refreshing Sicilian rosé makes the perfect Mediterranean aperitif companion" },
            { "item": "Antipasto Vegetable Blend", "why": "Italian pickled vegetables echo the wine's bright acidity and Mediterranean character" },
            { "item": "The Veg flatbread", "why": "Fresh vegetable flavors complement this mineral-driven Sicilian rosé perfectly" }
        ],
        "alcohol": "12.5%",
        "serving": "Well chilled (46-50°F / 8-10°C)",
        "notes": "Nerello Mascalese (neh-REH-loh mahs-kah-LEH-zeh) is Sicily's most celebrated grape, famous for volcanic Etna Rosso—sometimes compared to Burgundy for its elegance and age-worthiness. As a rosé, it expresses delicate red berry fruit, citrus blossom, and a distinctive saline minerality shaped by Mediterranean sea winds. 'Rosa Dei Venti' means 'Rose of the Winds'—a compass rose navigating wine lovers to something unexpected and beautiful. Gorghi Tondi's organic farming and proximity to the Sicilian coast give this rosé an unmistakably fresh, seaside character.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
        "archivedDate": "March 2026",
        "replacedBy": "Grape Abduction Company Orange",
    },
    {
        "name": "Long Valley Ranch",
        "vintage": "2023",
        "type": "red",
        "grape": "100% Cabernet Sauvignon",
        "grapeDetail": "Cabernet Sauvignon from Monterey County's warm inland valleys — estate-grown fruit with the structure and freshness that California's Central Coast climate produces so naturally.",
        "region": "Monterey County, California",
        "appellation": "Monterey County AVA",
        "country": "USA",
        "winemaker": "Long Valley Ranch — An estate vineyard producer in Monterey County, California's largest wine-producing county by acreage. Monterey sits along the Central Coast between San Francisco and Los Angeles, where the Salinas Valley channels cool Pacific air inland, moderating temperatures even in the warmest growing zones. Long Valley Ranch's estate vineyards in the warmer southern reaches of the county yield ripe, structured Cabernet Sauvignon with characteristic Central Coast freshness — California fruit richness with a cool-climate edge.",
        "tasting": "Dark cherry, ripe blackcurrant, cassis, hints of cedar and dried herbs. Medium to full body with smooth, well-integrated tannins and a clean, food-friendly finish.",
        "food": "Chorizo, Manchego, Ewephoria, Red Wine Cheddar, The Mighty Spicy flatbread",
        "foodPairings": [
            { "item": "Chorizo", "why": "Smoky paprika and dark fruit is a natural pairing — the wine's structure handles the richness" },
            { "item": "Manchego", "why": "Nutty sheep's milk cheese softens the tannins and echoes the wine's warm, ripe character" },
            { "item": "Ewephoria", "why": "Caramelized butterscotch notes balance the Cabernet's structure and dark fruit" },
            { "item": "Red Wine Cheddar", "why": "Wine-infused cheese creates harmony with the Cabernet's cassis and cedar character" },
            { "item": "The Mighty Spicy flatbread", "why": "Bold, spicy flavors stand up to this medium-full bodied wine" }
        ],
        "alcohol": "13.5%",
        "serving": "Room temperature (62-65°F / 17-18°C)",
        "notes": "Monterey County is California's largest wine-producing county by acreage — a sprawling Central Coast region stretching from Salinas in the north to Paso Robles in the south. The Salinas Valley is famous for its 'wind tunnel' effect: cool Pacific air funnels inland every afternoon, keeping temperatures 20–30 degrees cooler than the Central Valley even on hot days. This diurnal shift — warm mornings, cool afternoons and nights — gives Monterey wines natural freshness and acidity even in ripe varieties like Cabernet Sauvignon. Long Valley Ranch's estate fruit benefits from this climate, producing a Cab that's ripe and approachable without sacrificing structure or food-friendliness.",
        "pronunciation": None,
        "pronunciationGuideOnly": False,
        "archivedDate": "March 2026",
        "replacedBy": "L.A. Cetto",
    },
]

BEERS = [
    {
        "name": "Edmund's Oast Something Cold Blonde",
        "brewery": "Edmund's Oast Brewing Co.",
        "location": "Charleston, SC",
        "style": "Blonde Ale",
        "type": "ale",
        "abv": "5.0%",
        "body": "Light",
        "tasting": "Crisp, clean, subtle malt sweetness with light hop bitterness. Refreshing and highly drinkable with a smooth finish.",
        "notes": "A classic American Blonde Ale perfect for hot Charleston days. Edmund's Oast is a beloved local brewery known for approachable, well-crafted beers.",
    },
    {
        "name": "Citra Ass Down Double IPA",
        "brewery": "Against the Grain Brewery",
        "location": "Louisville, KY",
        "style": "Double IPA",
        "type": "ipa",
        "abv": "8.0%",
        "body": "Medium-Full",
        "tasting": "Intense tropical fruit, grapefruit, mango, passionfruit from Citra hops. Bold hop bitterness balanced by malt backbone with a warming finish.",
        "notes": "A hop-forward Double IPA showcasing the famous Citra hop variety. Despite the high ABV, it drinks smoothly with explosive tropical fruit character.",
    },
    {
        "name": "Shore Leave Lager",
        "brewery": "Westbrook Brewing Co.",
        "location": "Mt. Pleasant, SC",
        "style": "American Lager",
        "type": "lager",
        "abv": "4.5%",
        "body": "Light",
        "tasting": "Clean, crisp, refreshing with subtle grain character. Light floral hop notes and a dry, thirst-quenching finish.",
        "notes": "A no-frills, perfectly executed American lager from one of South Carolina's premier craft breweries. Ideal for easy drinking.",
    },
    {
        "name": "Revelry Poke the Bear",
        "brewery": "Revelry Brewing Co.",
        "location": "Charleston, SC",
        "style": "American Pale Ale",
        "type": "ale",
        "abv": "5.5%",
        "body": "Medium",
        "tasting": "Citrus, floral, and tropical fruit from American hops. Light malt backbone with moderate bitterness and a refreshing, clean finish.",
        "notes": "A refreshing American Pale Ale with bright hop character. Revelry is a Charleston favorite known for creative, quality beers.",
    },
    {
        "name": "Burial Surf Wax IPA",
        "brewery": "Burial Beer Co.",
        "location": "Asheville, NC",
        "style": "IPA",
        "type": "ipa",
        "abv": "6.8%",
        "body": "Medium",
        "tasting": "Citrus, tropical fruit, pine, resinous hops. Balanced bitterness with a dry, hoppy finish. Very aromatic.",
        "notes": "A West Coast-style IPA from one of Asheville's most acclaimed breweries. Burial is known for their artistic branding and exceptional hop-forward beers.",
    },
    {
        "name": "Revelry Lefty Loosey IPA",
        "brewery": "Revelry Brewing Co.",
        "location": "Charleston, SC",
        "style": "IPA",
        "type": "ipa",
        "abv": "7.0%",
        "body": "Medium",
        "tasting": "Bright citrus, grapefruit, tropical notes with balanced malt sweetness. Crisp bitterness and a refreshing finish.",
        "notes": "Revelry's flagship IPA - a crowd-pleasing, well-balanced American IPA that showcases modern hop flavors without being overwhelming.",
    },
    {
        "name": "Blue Moon Belgian White (Non-Alcoholic)",
        "brewery": "Blue Moon Brewing Co.",
        "location": "Golden, CO",
        "style": "Belgian-Style Wheat (NA)",
        "type": "other",
        "abv": "0.45%",
        "body": "Light-Medium",
        "tasting": "Orange peel, coriander, wheat, subtle sweetness. Creamy mouthfeel with citrus notes and a refreshing finish.",
        "notes": "The non-alcoholic version of the iconic Belgian-style wheat beer. Brewed with Valencia orange peel and coriander for signature Blue Moon flavor without the alcohol.",
    },
    {
        "name": "Exner Spanish Cider",
        "brewery": "Exner Cider",
        "location": "Asturias, Spain",
        "style": "Spanish Sidra Natural",
        "type": "other",
        "abv": "6.0%",
        "body": "Light-Medium",
        "tasting": "Tart apple, funky farmhouse notes, slight acidity, dry finish. Unfiltered with natural effervescence.",
        "notes": "Traditional Spanish sidra from Asturias, the cider capital of Spain. Traditionally poured from height (escanciar) to aerate and release aromatics. Dry, tart, and refreshingly different from sweet American ciders.",
    },
]

CHEESES = [
    {"name": "Black Truffle Goat", "price": "$9", "origin": "France", "type": "Goat, Soft and Ripened", "description": "A luxurious French goat cheese infused with earthy black truffle. Creamy, tangy, and aromatic with an unmistakable truffle flavor that lingers on the palate.", "pairings": "Domaine de la Petite Roche Anjou Cab Franc, Jean Aubron, Pouilly-Fumé Dezat, Red Tail Ridge Pinot Noir", "pronunciation": None},
    {"name": "Maple Bourbon Goat", "price": "$9", "origin": "Wisconsin, USA", "type": "Goat, Sweet, Fruity, Tangy", "description": "American artisan goat cheese with sweet maple and warm bourbon notes. The tangy goat milk base balances the sweetness perfectly. A unique sweet-savory experience.", "pairings": "Braunewell Scheurebe, pairs beautifully with aromatic whites", "pronunciation": None},
    {"name": "Saint Angel", "price": "$9", "origin": "France", "type": "Cow, Soft, Triple Crème", "description": "An indulgent triple-crème cheese (75% butterfat) from Burgundy. Incredibly rich, buttery, and cloud-like with a bloomy rind. Melts on the tongue like butter.", "pairings": "Gorghi Tondi Frappato, Red Tail Ridge Pinot Noir, Presqu'ile, Famiglia Boron", "pronunciation": None},
    {"name": "Ewephoria", "price": "$9", "origin": "Netherlands", "type": "Sheep, Firm, Aged Gouda", "description": "A sheep's milk Gouda aged 9+ months. Sweet, nutty, with butterscotch and caramel notes. Crunchy protein crystals add texture. The name is a play on 'euphoria.'", "pairings": "Domaine Verquière Plan de Dieu, Les Cousins L'Inconscient, Palmeri Navalta, Encomienda de Cervera Horten, Cims de Porrera Priorat", "pronunciation": None},
    {"name": "Smoked Chili Cheddar", "price": "$9", "origin": "Vermont, USA", "type": "Cow, Firm, Habanero", "description": "Sharp Vermont cheddar with smoky undertones and a habanero kick. The heat builds gradually while the smoke adds depth. Bold and memorable.", "pairings": "Orsa, Les Cousins L'Inconscient - bold wines to match the bold heat!", "pronunciation": None},
    {"name": "Mimolette", "price": "$9", "origin": "France", "type": "Cow, Firm, Sharp, Aged", "description": "A French cheese with a distinctive bright orange interior (from annatto). Aged versions develop nutty, butterscotch flavors and a slightly crumbly texture. Similar to aged Gouda.", "pairings": "Domaine Verquière Plan de Dieu, Les Cousins L'Inconscient, Palmeri Navalta, Château Roc Meynard, Cims de Porrera Priorat", "pronunciation": None},
    {"name": "Blue d'Auvergne", "price": "$9", "origin": "France", "type": "Cow, Semi-Firm, Tangy Blue", "description": "A classic French blue from the volcanic Auvergne region. Creamy with bold, tangy blue veins. Less intense than Roquefort, more approachable. Spicy and piquant.", "pairings": "Orsa, Les Cousins L'Inconscient - bold wines for bold cheese", "pronunciation": "doh-VAIRN-yuh"},
    {"name": "Red Wine Cheddar", "price": "$9", "origin": "Ireland", "type": "Cow, Semi-Firm, Fruity", "description": "Irish cheddar soaked in red wine, creating a beautiful purple marbled rind. Creamy, slightly tangy with subtle wine-infused fruity notes. Stunning presentation.", "pairings": "Les Cousins L'Inconscient, Encomienda de Cervera Horten, Domaine de la Petite Roche Anjou Cab Franc, Château Roc Meynard, Chianti Classico", "pronunciation": None},
    {"name": "Petit Basque", "price": "$9", "origin": "France", "type": "Sheep, Semi-Firm, Mild", "description": "A mild, approachable sheep's milk cheese from the French Pyrenees. Nutty, slightly sweet with a smooth, buttery texture. Great for those new to sheep's milk cheese.", "pairings": "Gorghi Tondi Frappato, Domaine de la Petite Roche Anjou Cab Franc, Jean Aubron, Pouilly-Fumé Dezat, Marola Albariño", "pronunciation": None},
    {"name": "Gruyère", "price": "$9", "origin": "Switzerland", "type": "Cow, Semi-Firm, Swiss", "description": "The king of Swiss cheeses. Aged 5+ months, it develops complex nutty, earthy flavors with a slight sweetness. Perfect for melting but equally delicious on a board.", "pairings": "Chianti Classico, Montepulciano d'Abruzzo, Ercole Barbera, Presqu'ile", "pronunciation": "groo-YAIR"},
    {"name": "Honey Bee Gouda", "price": "$9", "origin": "Netherlands", "type": "Goat, Firm, Honey Infused", "description": "A Dutch goat's milk Gouda with clover honey crystals throughout. Sweet, tangy, and utterly unique. The honey complements the goat's milk tanginess beautifully.", "pairings": "Presqu'ile, pairs well with sweeter/richer whites", "pronunciation": None},
    {"name": "Pecorino Toscano", "price": "$9", "origin": "Tuscany, Italy", "type": "Sheep, Semi-Firm, Mild", "description": "A classic Tuscan sheep's milk cheese. Mild and milky when young, developing nuttier, more complex flavors with age. The name means 'Tuscan sheep.' A natural partner for Tuscan wines.", "pairings": "Chianti Classico — perfect regional match; Montepulciano d'Abruzzo", "pronunciation": None},
]

CHARCUTERIE = [
    {"name": "Salchichón De Bellota", "price": "$13", "origin": "Spain", "type": "Ibérico Salami, Acorn-Fed", "description": "The pinnacle of Spanish cured meats. Made from acorn-fed (bellota) Ibérico pigs, which roam oak forests eating only acorns. Rich, nutty, with a melt-in-your-mouth texture. Worth every penny.", "pairings": "Domaine Verquière Plan de Dieu, Les Cousins L'Inconscient, Palmeri Navalta, Encomienda de Cervera Horten", "pronunciation": "sal-chee-CHOHN deh beh-YOH-tah"},
    {"name": "Felino Salami", "price": "$9", "origin": "Italy", "type": "Peppercorn and Red Wine, Pork", "description": "A classic Italian salami from Parma, seasoned with peppercorns and red wine. Delicate, mildly sweet with a silky texture. Named after the town of Felino near Parma.", "pairings": "Chianti Classico, Montepulciano d'Abruzzo, Ercole Barbera - classic Italian pairings", "pronunciation": None},
    {"name": "Black Pepper Salami", "price": "$9", "origin": "France", "type": "Rolled in Black Pepper, Pork", "description": "French dry-cured salami with a generous black pepper crust. The pepper adds a spicy bite that contrasts the fatty, savory pork interior. Rustic and satisfying.", "pairings": "Domaine Verquière Plan de Dieu, Domaine de la Petite Roche Anjou Cab Franc, Château Roc Meynard, Rosé - French wines for French salami", "pronunciation": None},
    {"name": "Bresaola", "price": "$9", "origin": "Italy", "type": "Italian Lean Cured Beef", "description": "Air-dried, salted beef from Lombardy. Deep ruby red, lean, and delicate with a subtle, slightly sweet flavor. Often served with olive oil and lemon.", "pairings": "Orsa, Pouilly-Fumé Dezat, Marola Albariño, Pinot Grigio", "pronunciation": "breh-ZOW-lah"},
    {"name": "Prosciutto di Parma", "price": "$9", "origin": "Italy", "type": "Italian Cured Pork Ham", "description": "The world's most famous cured ham. Aged 12+ months in Parma, where the sea air and tradition create silky, nutty, sweet slices of perfection. DOP protected.", "pairings": "Gorghi Tondi Frappato, Chianti Classico, Ercole Barbera, Jean Aubron, Pinot Grigio, Rosé", "pronunciation": "proh-SHOO-toh dee PAR-mah"},
    {"name": "Hot Coppa", "price": "$9", "origin": "Italy", "type": "Cured Spicy Pork, Paprika", "description": "Dry-cured pork shoulder (capocollo) with hot paprika. Marbled with fat, spicy, and deeply savory. The heat is present but not overwhelming. A spice-lover's delight.", "pairings": "Les Cousins L'Inconscient, Orsa - bold wines for spicy meat", "pronunciation": None},
    {"name": "Soppressata Salame w/ Burgundy", "price": "$9", "origin": "Italy", "type": "Italian Dried Salami infused with Burgundy wine", "description": "Traditional Italian soppressata infused with Burgundy wine. Coarse-ground, well-marbled, with wine adding fruity depth. The wine tenderizes and flavors the meat beautifully.", "pairings": "Domaine Verquière Plan de Dieu, Domaine de la Petite Roche Anjou Cab Franc, Château Roc Meynard - French wines complement the Burgundy", "pronunciation": None},
    {"name": "Chorizo", "price": "$9", "origin": "Spain", "type": "Spanish Dried Salami, Paprika", "description": "Spanish dry-cured sausage with smoked paprika (pimentón). Deep red color, smoky, slightly spicy. The signature taste of Spain. Not to be confused with Mexican fresh chorizo.", "pairings": "Domaine Verquière Plan de Dieu, Les Cousins L'Inconscient, Heretat Mont-Rubí, Encomienda de Cervera Horten, Orsa, Cims de Porrera Priorat", "pronunciation": None},
    {"name": "Black Truffle Salami", "price": "$13", "origin": "France", "type": "Pork, Earthy", "description": "French artisan salami studded with real black truffle pieces. Rich pork flavor elevated by earthy, aromatic truffle. A luxurious upgrade to any charcuterie board.", "pairings": "Encomienda de Cervera Horten, Ercole Barbera, Palmeri Navalta - wines that match its intensity", "pronunciation": None},
]

FLATBREADS = [
    {"name": "The Basque", "price": "$15", "type": "Fig Jam, Black Truffle Goat, Prosciutto", "description": "Sweet fig jam meets earthy truffle goat cheese, topped with silky prosciutto. A perfect balance of sweet, savory, and earthy. Our most popular flatbread.", "pairings": "Gorghi Tondi Frappato, Montepulciano d'Abruzzo, Ercole Barbera", "origin": None, "pronunciation": None},
    {"name": "The Mighty Spicy", "price": "$14", "type": "Smoked Chili Cheddar, Chorizo, Mushroom, Olives", "description": "For heat-seekers! Spicy cheddar and smoky chorizo with earthy mushrooms and briny olives. Bold, spicy, and deeply satisfying. Bring water.", "pairings": "Cims de Porrera Priorat, Les Cousins L'Inconscient, Orsa", "origin": None, "pronunciation": None},
    {"name": "The Veg", "price": "$14", "type": "Gruyère, Sun Dried Tomatoes, Olives", "description": "Nutty Gruyère with sweet sun-dried tomatoes and briny olives. Vegetarian but never boring. Mediterranean-inspired and utterly delicious.", "pairings": "Jean Aubron, Pouilly-Fumé Dezat, Rosé", "origin": None, "pronunciation": None},
]

TAPAS = [
    {"name": "Tapenade", "price": "$9", "type": "Olive Dip", "description": "Classic Provençal olive spread made from black olives, capers, anchovies, and olive oil. Briny, savory, and intensely Mediterranean. Perfect with crusty bread.", "pairings": "Domaine Verquière Plan de Dieu, Heretat Mont-Rubí, Rosé, Marola Albariño", "origin": None, "pronunciation": None},
    {"name": "Hummus", "price": "$7", "type": "Chickpea Dip", "description": "Creamy, garlicky chickpea dip with tahini and lemon. A crowd-pleaser that goes with almost everything. Smooth, tangy, and utterly satisfying.", "pairings": "Braunewell Scheurebe, Jean Aubron, Pouilly-Fumé Dezat, Marola Albariño, Pinot Grigio, Rosé", "origin": None, "pronunciation": None},
    {"name": "Pimento Cheese Dip", "price": "$7", "type": "with Jalapeño, Made Locally", "description": "A Southern classic with a kick! Sharp cheddar, roasted pimentos, and fresh jalapeño made by a local producer. Creamy, cheesy, and spicy. Pairs great with crackers.", "pairings": "Braunewell Scheurebe, Orsa - the aromatic fruit of Scheurebe balances the heat", "origin": None, "pronunciation": None},
    {"name": "Antipasto Vegetable Blend", "price": "$6", "type": "Assortment of Pickled Vegetables", "description": "Italian-style pickled vegetables including artichokes, peppers, and more. Tangy, crunchy, and bright. A refreshing palate cleanser between rich bites.", "pairings": "Chianti Classico, Montepulciano d'Abruzzo, Marola Albariño, Pinot Grigio", "origin": None, "pronunciation": None},
    {"name": "Whipped Honey Goat Cheese", "price": "TBD", "type": "Small Bowl, Topped with Walnuts, Dried Cranberries & Honey", "description": "Light, airy whipped goat cheese served in a small bowl and topped with crunchy walnuts, sweet-tart dried cranberries, and a drizzle of honey. Creamy, sweet, tangy, and texturally delightful.", "pairings": "Braunewell Scheurebe, Presqu'ile, Rosé - aromatic whites complement the honey and tangy goat cheese", "origin": None, "pronunciation": None},
    {"name": "Compound Butter Duo", "price": "$12", "type": "Italian Herb & Maple Cinnamon, with Baguette", "description": "Two house-made compound butters—savory Italian Herb and sweet Maple Cinnamon—served with warm baguette. A delightful way to start your visit.", "pairings": "Presqu'ile, Braunewell Scheurebe, Rosé", "origin": None, "pronunciation": None},
]

PATES = [
    {"name": "Duck Rillettes", "price": "$11", "origin": "France", "type": "Duck Confit Pâté", "description": "Shredded duck confit slowly cooked in its own fat until silky and spreadable. Rich, deeply savory, with a rustic texture. A French bistro classic.", "pairings": "Domaine de la Petite Roche Anjou Cab Franc, Massimo Ribeira Sacra, Red Tail Ridge Pinot Noir, Château Roc Meynard, L.A. Cetto", "pronunciation": "ree-YEHT"},
    {"name": "Pâté de Campagne", "price": "$10", "origin": "France", "type": "Pork, Country Style", "description": "Rustic French country pâté made from coarsely ground pork with herbs and spices. Dense, meaty, and earthy. The everyday pâté of the French countryside.", "pairings": "Domaine de la Petite Roche Anjou Cab Franc, Château Roc Meynard, Domaine Verquière Plan de Dieu - French wines that complement rustic country pâté", "pronunciation": "pah-TAY duh kahm-PAHN-yuh"},
    {"name": "Foie Gras with Black Truffle", "price": "$13", "origin": "France", "type": "Goose Liver with Black Truffles", "description": "The ultimate luxury. Silky goose liver pâté studded with black truffle. Buttery, rich, and incredibly decadent. A truly special experience. Serve with toast points.", "pairings": "Red Tail Ridge Pinot Noir, Presqu'ile, Heretat Mont-Rubí", "pronunciation": "fwah GRAH"},
]

DESSERTS = [
    {"name": "Lemoncello Tartufo", "price": "$8", "type": "Lemon Ice Cream with Lemon Confit", "description": "Italian frozen dessert with creamy lemon ice cream, candied lemon confit, and a boozy limoncello kick. Bright, refreshing, and the perfect palate cleanser.", "pairings": "Braunewell Scheurebe - aromatic fruit pairs beautifully with citrus", "origin": None, "pronunciation": None},
    {"name": "Baby Cakes Petit Fours", "price": "$15", "type": "Assortment of 6 Mini Cakes", "description": "Six delicate bite-sized cakes from Baby Cakes bakery. Elegant, sweet, and beautifully made — the perfect sweet finale to share.", "pairings": "Presqu'ile — bright acidity balances the sweetness beautifully", "origin": None, "pronunciation": None},
    {"name": "Exotic Bomba", "price": "$12", "type": "Mango, Passion Fruit & Raspberry Sorbetta, coated in White Chocolate", "description": "A tropical explosion! Three layers of exotic fruit sorbetto encased in white chocolate. Bright, fruity, refreshing, and visually stunning.", "pairings": "Braunewell Scheurebe - aromatic Scheurebe loves tropical fruit", "origin": None, "pronunciation": None},
]
